### ISSUE TITLE
Error Occurs When Using a Model Trained on a Custom Dataset in demo.py

### ISSUE THREAD

**Issue by ckdghks** [jchenghu/ExpansionNet_v2#20]
I have trained the ExpansionNet model using a Korean dataset. After training, I tried to load the trained model in demo.py for a demo, but encountered the following error. 
![image](https://github.com/user-attachments/assets/d645b1bb-d9ce-4c17-bd2d-563b74afa8bc)

How should I debug this error? Is there a possibility that I made a mistake during the model training? The model training process was completed up to the 6th step.

**Comment by jchenghu** [comment]
Hi, 

Your training and implementation should work fine. The error says that the current model declaration is based on the English dictionary, which was made of 10.000 tokens, yours instead seems to be made of 18.878 Korean tokens.

I personally made a mistake during the design of checkpoint files: it should have contained the dictionary as well. 
Because I did not in this version, the demo requires both a checkpoint and the tokens dictionary (the pickle).

To fix this bug, you can simply replace the english dictionary in the pickle file with your dictionary, based on the Korean language.

The current implementation loads this file `'./demo_material/demo_coco_tokens.pickle'`
```
    with open('./demo_material/demo_coco_tokens.pickle', 'rb') as f:
        coco_tokens = pickle.load(f)
        sos_idx = coco_tokens['word2idx_dict'][coco_tokens['sos_str']]
        eos_idx = coco_tokens['word2idx_dict'][coco_tokens['eos_str']]
```

you can modify temporarily the `train.py` and insert the following lines right after the dataset creation:

```
coco_dataset = <your dataset>

import pickle
    with open('./demo_material/demo_coco_tokens_korean.pickle', 'wb') as f:
        demo_tokens = dict()
        demo_tokens['word2idx_dict'] = coco_dataset.caption_word2idx_dict
        demo_tokens['idx2word_list'] = coco_dataset.caption_idx2word_list
        demo_tokens['sos_str'] = coco_dataset.get_sos_token_str()
        demo_tokens['eos_str'] = coco_dataset.get_eos_token_str()
        pickle.dump(demo_tokens, f)
exit(-1)
```

then go back to the demo.py and change the path from `./demo_material/demo_coco_tokens.pickle` to `./demo_material/demo_coco_tokens_korean.pickle`

**Comment by ckdghks** [comment]
Thank you for the quick and accurate response! I was able to resolve the error using the answer you provided. Thanks again
